-- Admin Editor global settings + audit history
create table if not exists public.admin_editor_settings (
  id integer primary key check (id = 1),
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_editor_history (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  summary text,
  created_at timestamptz not null default now()
);

alter table public.admin_editor_settings enable row level security;
alter table public.admin_editor_history enable row level security;

drop policy if exists "admin editor settings read" on public.admin_editor_settings;
create policy "admin editor settings read" on public.admin_editor_settings
for select to authenticated
using (exists (select 1 from public.admin_users au where au.id=auth.uid() and lower(coalesce(au.status,'active'))='active'));

drop policy if exists "admin editor settings write" on public.admin_editor_settings;
create policy "admin editor settings write" on public.admin_editor_settings
for insert to authenticated
with check (exists (select 1 from public.admin_users au where au.id=auth.uid() and lower(coalesce(au.status,'active'))='active'));

drop policy if exists "admin editor settings update" on public.admin_editor_settings;
create policy "admin editor settings update" on public.admin_editor_settings
for update to authenticated
using (exists (select 1 from public.admin_users au where au.id=auth.uid() and lower(coalesce(au.status,'active'))='active'))
with check (exists (select 1 from public.admin_users au where au.id=auth.uid() and lower(coalesce(au.status,'active'))='active'));

drop policy if exists "admin editor history read" on public.admin_editor_history;
create policy "admin editor history read" on public.admin_editor_history
for select to authenticated
using (exists (select 1 from public.admin_users au where au.id=auth.uid() and lower(coalesce(au.status,'active'))='active'));

drop policy if exists "admin editor history insert" on public.admin_editor_history;
create policy "admin editor history insert" on public.admin_editor_history
for insert to authenticated
with check (admin_id=auth.uid() and exists (select 1 from public.admin_users au where au.id=auth.uid() and lower(coalesce(au.status,'active'))='active'));

create index if not exists idx_admin_editor_history_created_at on public.admin_editor_history(created_at desc);

insert into public.admin_editor_settings(id,settings)
values (1,'{}'::jsonb)
on conflict (id) do nothing;
