-- ADMIN EDITOR GLOBAL SETTINGS
-- Run this SQL once in Supabase SQL Editor.
-- Scope: Admin Editor only. No existing application/user/payment/CMS data is changed.

create table if not exists public.admin_editor_settings (
  id text primary key default 'global',
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_editor_change_log (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('save','reset')),
  settings jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_editor_change_log_created_at_idx
  on public.admin_editor_change_log(created_at desc);

alter table public.admin_editor_settings enable row level security;
alter table public.admin_editor_change_log enable row level security;

create or replace function public.admin_editor_is_authorized()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  ok boolean;
begin
  select exists (
    select 1
    from public.admin_users au
    where au.id = auth.uid()
      and lower(coalesce(au.status,'active')) = 'active'
  ) into ok;
  return coalesce(ok,false);
end;
$$;

create or replace function public.admin_editor_get()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.admin_editor_is_authorized() then
    raise exception 'Admin access required';
  end if;
  select settings into result
  from public.admin_editor_settings
  where id='global';
  return result;
end;
$$;

create or replace function public.admin_editor_save(p_settings jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  clean jsonb;
begin
  if not public.admin_editor_is_authorized() then
    raise exception 'Admin access required';
  end if;
  if jsonb_typeof(p_settings) <> 'object' then
    raise exception 'Invalid Admin Editor settings';
  end if;

  clean := p_settings;
  insert into public.admin_editor_settings(id,settings,updated_by,updated_at)
  values('global',clean,auth.uid(),now())
  on conflict(id) do update set settings=excluded.settings,updated_by=excluded.updated_by,updated_at=now();

  insert into public.admin_editor_change_log(admin_id,action,settings)
  values(auth.uid(),'save',clean);

  return clean;
end;
$$;

create or replace function public.admin_editor_reset()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  empty jsonb := '{}'::jsonb;
begin
  if not public.admin_editor_is_authorized() then
    raise exception 'Admin access required';
  end if;

  delete from public.admin_editor_settings where id='global';
  insert into public.admin_editor_change_log(admin_id,action,settings)
  values(auth.uid(),'reset',empty);

  return empty;
end;
$$;

revoke all on table public.admin_editor_settings from anon, authenticated;
revoke all on table public.admin_editor_change_log from anon, authenticated;
revoke all on function public.admin_editor_is_authorized() from public;
revoke all on function public.admin_editor_get() from public;
revoke all on function public.admin_editor_save(jsonb) from public;
revoke all on function public.admin_editor_reset() from public;

grant execute on function public.admin_editor_get() to authenticated;
grant execute on function public.admin_editor_save(jsonb) to authenticated;
grant execute on function public.admin_editor_reset() to authenticated;
